name: Process Sprite Sheet

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nome del file immagine caricato (es. ash.png)'
        required: true
        default: 'input.png'

jobs:
  run-python-script:
  runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        IMAGE_PATH: ${{ github.event.inputs.image_name }}
      run: |
        python script.py
